import Navigation from "@/components/navigation";
import { cn } from "@/libs/utils";
import "@/styles/customTheme.css";
import "@/styles/globals.css";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body>
        <Navigation />
        <main className={cn("container", "pt-16")}>{children}</main>
      </body>
    </html>
  );
}
